flamingock:
  stages:
    - name: stage1
      code-packages:
        - io.flamingock.examples.mongodb.springboot.springdata.changes
        - io.flamingock.examples.mongodb.springboot.springdata.mongock
  transactionEnabled: true
  legacy-mongock-changelog-source: mongockChangeLog
