flamingock:
  stages:
    - name: stage1
      code-packages:
        - io.flamingock.examples.mongodb.springboot.springdata.changes
  transactionEnabled: true
  mongock-importer-source: mongockChangeLog
