flamingock:
  stages:
    - name: stage1
      code-packages:
        - io.flamingock.examples.mongodb.springboot.sync.changes
  transactionDisabled: false

spring:
  profiles:
    active:
      - accepted-profile-1
      - accepted-profile-2
      - not-used-profile






